---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp2
 labels:
  app: myapp2
spec:
 replicas: 2
 selector:
  matchLabels:
   app: myapp2
 template:
  metadata: 
   labels:
    app: myapp2
  spec:
   containers:
   - name: myapp2
     image: "gcr.io/protean-booth-260117/tamilarasanece1989/devops1:tagversion"
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  type: LoadBalancer
  selector:
    app: myapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
